---
- name: Déploiement de FusionInventory agent
  hosts: pc1, pc2, pc3
  become: true

  tasks:
    - name: mise a jour
      command:
        apt update --allow-releaseinfo-change

    - name: apt update
      apt:
        update_cache: yes

    - name: Installation de fusionInventory
      apt:
        name: fusioninventory-agent
        state: latest 

    - name: Paramétrage de l'agent
      lineinfile:
        path: /etc/fusioninventory/agent.cfg
        line: "server = http://192.168.57.98/glpi/plugins/fusioninventory/"

    - name: demarrer le service 
      service:
        name: fusioninventory-agent
        state: started

    - name: demarrer service
      command:
        fusioninventory-agent 

    -  name: Installation de snmp
       apt:
         name: snmpd
         state: latest
    
    - name: Paramétrage de snmp
      lineinfile:
        path: /etc/snmp/snmpd.conf
        line: "agentAddress udp:161,udp6:[::1]:161"
        line: "rocommunity example"
        line: "agentAddress udp:161,udp6:[::1]:161"
        
    - name: demarrer le service
      service:
        name: snmpd
        state: started