#!/usr/bin/python3
# Script pour avoir la liste des ordinateurs d'un inventaire GLPI
import requests
import base64
USER = 'glpi'
PASSWORD = 'tprli'
URL = 'http://192.168.57.98/glpi/apirest.php/'
APP_TOKEN = '1b2c3d4e5f6g7h8i9j0k'

# (USER:PASSWORD -> base64)
p = USER + ':' + PASSWORD
authtoken = base64.b64encode(bytes(p, 'utf-8')) # bytes
authtoken = str(authtoken)[2:-1]
# Récupération du token
# CURL -s -X GET -H 'Content-Type: application/json' -H 'Authorization: Basic $authtoken' -H 'App-Token: $apptoken' $url/initSession/
headers= {
		'Content-Type': 'application/json',
		'Authorization': 'Basic ' + authtoken,
		'App-Token': APP_TOKEN
	}
response = requests.get(
	URL + 'initSession/',
	headers= headers
)

if response.status_code == 200:
	token = response.json()['session_token']
else:
	print('Erreur lors de la récupération du token')
	print(response.json())
	exit(1)

# Récupération de la liste des ordinateurs
headers = {
		'Content-Type': 'application/json',
		'Session-Token': str(token),
		'App-Token': APP_TOKEN
	}
response = requests.get(
	URL + 'Computer/',
	headers= headers
)

if response.status_code == 200:
	response = response.json()
else:
	print('Erreur lors de la récupération de la liste des ordinateurs')
	print(response.json())
	exit(1)

res = { "all": {
	"hosts": []
}}

for entries in response:
	res["all"]["hosts"].append(entries["name"])

print(res)
