#!/usr/bin/python3
# Script pour avoir la liste des ordinateurs d'un inventaire GLPI
import requests
import base64

# Variables
USER = 'glpi'
PASSWORD = 'tprli'
URL = 'http://192.168.57.98/glpi/apirest.php/'
APP_TOKEN = '1b2c3d4e5f6g7h8i9j0k'
NAGIOS_PATH = '/etc/nagios4/objects/'

def get_inventory():
	# Création du token
	authtoken = str(base64.b64encode(bytes(USER+ ":" + PASSWORD, 'utf-8')))[2:-1]

	# Récupération du token
	response = requests.get(
		URL + 'initSession/',
		headers= {
			'Content-Type': 'application/json',
			'Authorization': 'Basic ' + authtoken,
			'App-Token': APP_TOKEN
		}
	)

	if response.status_code == 200:
		token = response.json()['session_token']
	else:
		print('Erreur lors de la récupération du token')
		exit(1)

	# Récupération de la liste des ordinateurs
	response = requests.get(
		URL + 'Computer/',
		headers= {
			'Content-Type': 'application/json',
			'Session-Token': str(token),
			'App-Token': APP_TOKEN
		}
	)

	if response.status_code == 200:
		response = response.json()
	else:
		print('Erreur lors de la récupération de la liste des ordinateurs')
		exit(1)

	return response

def format_ansible(inv):
	# Création des fichiers d'inventaire
	res = { "all": {
		"hosts": []
	}}

	for entries in inv:
		res["all"]["hosts"].append(entries["name"])

	return res

def write_cfg_each_host(inv):
	""" On écrit un fichier de configuration par host
	"""
	for host in inv:
		# On ouvre le fichier
		f = open(NAGIOS_PATH + host["name"] + ".cfg", "w")

		# On écrit le fichier
		f.write("define host {\n")
		f.write("\tuse\tlinux-server\n")
		f.write("\thost_name\t" + host["name"] + "\n")
		f.write("\tcheck_interval\t1\n")
		f.write("\t}")

inv = get_inventory()

inv_ansible = format_ansible(inv)


